config/routes.rb
Rails.application.routes.draw do

  namespace :admin do

    resources :orders
    resources :banners
    resources :email_marketings
    resources :offers

    resources :blogs
    resources :sliders
    resources :customers , only: [:index,:edit,:update,:destroy]



    resources :categories

    resources :products

    resources :settings


    resources :products do
      member do
        delete :delete_image_attachment
      end
    end
    resources :categories do
      member do
        delete :delete_image_attachment
      end
    end



  end

# get "blogs", to: 'blogs#index'



  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      confirmations: 'users/confirmations',
  }

  devise_for :customers, controllers: {
      sessions: 'customers/sessions',
      registrations: 'customers/registrations',
      passwords: 'customers/passwords',
      confirmations: 'customers/confirmations',
  }

  resources :users


  get "/admin", to: 'admin/dashboard#index'

  root 'admin/dashboard#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/banner.rb
require 'Attachment'
class Admin::Banner < ApplicationRecord
  include Attachment
  # accept banner image
  has_one_attached :image

  # velidate image only
  validate :validate_image

end

app/models/admin/blog.rb
require 'Attachment'

class Admin::Blog < ApplicationRecord

  include Attachment

  has_one_attached :image

  # validate image file
  validate :validate_image



end

app/models/admin/category.rb
class Admin::Category < ApplicationRecord

  #upload category image
  has_one_attached :image

  #define validations
  validates :name, :status , presence:true


  #relation with products table one to many
  has_many :products, dependent: :destroy



  # category image resize
  def preview

    self.image.variant(resize: '40x40!').processed
  end

  def thumbnail
    self.image.variant(resize: '100x100!').processed
  end



end

app/models/admin/customer.rb
class Admin::Customer < ApplicationRecord


end

app/models/admin/email_marketing.rb
class Admin::EmailMarketing < ApplicationRecord

  attr_accessor :send_type, :custom_email

  validates :sender_email ,  presence: true

end

app/models/admin/offer.rb
class Admin::Offer < ApplicationRecord

  require 'securerandom'

  # attr_accessor :offer_code

  before_validation(:on => :create) do
    self.offer_code = SecureRandom.hex(6)
  end

  validates :offer_name, :offer_value, :minimum_value, :start_date, :end_date, :status , presence: true
  validates :offer_value, numericality: true

end

app/models/admin/order.rb
class Admin::Order < ApplicationRecord
end

app/models/admin/product.rb
class Admin::Product < ApplicationRecord
  require 'securerandom'
  attr_accessor :name
  #upload single image
 # has_one_attached :item_images
  #upload multiple image
  has_many_attached :item_images

  validate :correct_image_type
  #realtion with category table many to one
  belongs_to :category

  before_validation(:on => :create) do
    self.item_code = SecureRandom.hex(6)
  end



  #resize image
  def small input
    return self.item_images[input].variant(resize: '80x80!').processed
  end

  def thumbnail input
    return self.item_images[input].variant(resize: '300x300!').processed
  end

  def banner
    return self.item_images.variant(resize: '900x200!').processed
  end


  private

  def correct_image_type
   if item_images.attached? == false
      errors.add(:item_images, "must have a image attached")
     elsif  item_images.each do |img|
         if !img.content_type.in?(%{image/jpeg image/png})
         errors.add(:item_images, "must be a jpeg or png")
         end
      end
    end
  end


  end

app/models/admin/setting.rb
class Admin::Setting < ApplicationRecord
  has_one_attached :logo
  has_one_attached :fevicon

  def logo_thumbnail
    self.logo.variant(resize: '100x100!').processed
  end

  def fevicon_thumbnail
    self.fevicon.variant(resize: '100x100!').processed
  end

end

app/models/admin/slider.rb
require 'Attachment'

class Admin::Slider < ApplicationRecord
  include Attachment
  # upload slider image
  has_one_attached :image

  validate :validate_image



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
require 'Attachment'

class Customer < ApplicationRecord
  include Attachment
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image
  validate :validate_image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/admin/banners_controller.rb
require 'Utlis'

class Admin::BannersController < ApplicationController
  include Utlis
  before_action :set_banner, only: [:show, :edit, :update, :destroy]
  before_action :set_status, only: [:new,:create,:edit,:update]
  before_action :authenticate_user!

  # GET /banners
  # GET /banners.json
  def index
    @banners = Admin::Banner.all
  end

  # GET /banners/1
  # GET /banners/1.json
  def show
  end

  # GET /banners/new
  def new
    @banner = Admin::Banner.new
  end

  # GET /banners/1/edit
  def edit
  end

  # POST /banners
  # POST /banners.json
  def create
    @banner = Admin::Banner.new(banner_params)

    respond_to do |format|
      if @banner.save
        format.html { redirect_to admin_banners_path, notice: 'Banner was successfully created.' }
        format.json { render :show, status: :created, location: @banner }
      else
        format.html { render :new }
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /banners/1
  # PATCH/PUT /banners/1.json
  def update
    respond_to do |format|
      if @banner.update(banner_params)
        format.html { redirect_to admin_banners_path, notice: 'Banner was successfully updated.' }
        format.json { render :show, status: :ok, location: @banner }
      else
        format.html { render :edit }
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /banners/1
  # DELETE /banners/1.json
  def destroy
    @banner.destroy
    respond_to do |format|
      format.html { redirect_to admin_banners_url, notice: 'Banner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_banner
      @banner = Admin::Banner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def banner_params
      params.require(:admin_banner).permit(:title, :link, :status, :image)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/helpers/admin/banners_helper.rb
module Admin::BannersHelper
end

app/helpers/admin/blogs_helper.rb
module Admin::BlogsHelper
end

app/helpers/admin/offers_helper.rb
module Admin::OffersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin/sliders_helper.rb
module Admin::SlidersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def controller?(*controller)
    controller.include?(params[:controller])
  end

  def action?(*action)
    action.include?(params[:action])
  end


  # view content status to list
  def status_tag(status)
    if status == 1
      content_tag( :span , "Active", :class => "label label-success")
    else
      content_tag( :span , "DeActive", :class => "label label-warning")
    end
  end

end

app/views/admin/banners/_form.html.erb
<!-- general form elements disabled -->
<div class="col-md-8 col-md-offset-2">
  <br/>
  <br/>
  <div class="box box-warning">
    <div class="box-header with-border">
      <h3 class="box-title"><%= title %></h3>
    </div>

    <!-- /.box-header -->
    <div class="box-body">

      <% if banner.errors.any? %>

        <div class="alert alert-danger alert-dismissible">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <h4><i class="icon fa fa-ban"></i> Validations Errors!</h4>

          <ul>
            <% banner.errors.full_messages.each do  |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>

      <% end %>

      <%= form_with(model: banner, local: true) do |form|  %>

        <!-- text input -->
        <div class="form-group">
          <%= form.label :title %>
          <%= form.text_field :title, :class=> "form-control", :placeholder => "Enter ..." %>
        </div>

        <!-- text input -->
        <div class="form-group">
          <%= form.label :status %>
          <%= form.select "status", options_for_select(@status.map { |obj| [obj['name'], obj['value']] }, form.object.status ), {} , {:class => 'form-control'} %>
        </div>

        <!-- text input -->
        <div class="form-group">
          <%= form.label :link %>
          <%= form.text_field :link, :class=> "form-control", :placeholder => "Enter ..." %>
        </div>


        <div class="form-group">
          <%= form.label :banner_image %>
          <div class="row">
            <% if form.object.image.attached? && form.object.image.content_type.in?("%{image/jpeg,image/png,image/jpg}")  %>
              <%= image_tag form.object.image.variant(resize: '200x100!').processed  %>

              <%= link_to "Delete", delete_image_attachment_admin_category_url(form.object.image.id),
                          method: :delete,
                          data: { confirm: 'Are you sure?' },  :class => "label label-danger" %>
            <% end %>
          </div>

          <%= form.file_field :image, :class => "form-control" %>
        </div>

        <%= form.submit :class => "btn btn-success pull-right" %>



      <% end %>




      <%= link_to "Back" , admin_banners_path , :class => "btn btn-warning "%>

    </div>
  </div>
</div>

app/views/admin/banners/edit.html.erb
<%= render 'form', banner: @banner, title: "Edit Banner" %>

app/views/admin/banners/index.html.erb
<div class="box">
  <div class="box-header">
    <h3 class="box-title">Banners </h3>
    <div class="pull-right">
      <%= link_to "Add New", new_admin_banner_path, :class => "btn btn-primary"  %>
    </div>

    <div class="row">
      <% if notice %>
        <div class="col-md-6 col-md-offset-3">
          <div class="alert alert-success alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <h4><i class="icon fa fa-check"></i> Message!</h4>
            <%= notice %>
          </div>
        </div>
      <% end %>
    </div>


  </div>
  <!-- /.box-header -->
  <div class="box-body">

    <table id="example1" class="table table-bordered table-striped">
      <thead>
      <tr>
        <th>Title</th>
        <th>Status</th>
        <th>Link</th>
        <th>Image</th>
        <th>Action</th>
      </tr>
      </thead>
      <tbody>
      <% @banners.each do |banner| %>

        <tr>
          <td><%= banner.title %></td>
          <td> <%= status_tag(banner.status) %>  </td>
          <td><%= banner.link %></td>
          <td>
            <% if banner.image.attached? %>
              <%= image_tag banner.image.variant(resize: '100x50!').processed %>
            <% end %>

          </td>
          <td>

            <%= link_to edit_admin_banner_path(banner) , :class=> "btn btn-success" do %>
              <%= fa_icon "edit" %>
            <% end %>

            <%= link_to banner, method: :delete , data: { confirm: "Are you sure ? "} ,:class =>"btn btn-danger" do %>
              <%= fa_icon "trash" %>
            <% end %>

          </td>
        </tr>

      <% end %>


      </tbody>
    </table>
  </div>
</div>

app/views/admin/banners/new.html.erb
<%= render 'form', banner: @banner, title: "Add new banner" %>

app/views/admin/banners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @banner.title %>
</p>

<p>
  <strong>Link:</strong>
  <%= @banner.link %>
</p>

<p>
  <strong>Status:</strong>
  <%= @banner.status %>
</p>

<%= link_to 'Edit', edit_banner_path(@banner) %> |
<%= link_to 'Back', banners_path %>