config/routes.rb
Rails.application.routes.draw do

  namespace :admin do

    resources :orders
    resources :banners
    resources :email_marketings
    resources :offers

    resources :blogs
    resources :sliders
    resources :customers , only: [:index,:edit,:update,:destroy]



    resources :categories

    resources :products

    resources :settings


    resources :products do
      member do
        delete :delete_image_attachment
      end
    end
    resources :categories do
      member do
        delete :delete_image_attachment
      end
    end



  end

# get "blogs", to: 'blogs#index'



  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      confirmations: 'users/confirmations',
  }

  devise_for :customers, controllers: {
      sessions: 'customers/sessions',
      registrations: 'customers/registrations',
      passwords: 'customers/passwords',
      confirmations: 'customers/confirmations',
  }

  resources :users


  get "/admin", to: 'admin/dashboard#index'

  root 'admin/dashboard#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/banner.rb
require 'Attachment'
class Admin::Banner < ApplicationRecord
  include Attachment
  # accept banner image
  has_one_attached :image

  # velidate image only
  validate :validate_image

end

app/models/admin/blog.rb
require 'Attachment'

class Admin::Blog < ApplicationRecord

  include Attachment

  has_one_attached :image

  # validate image file
  validate :validate_image



end

app/models/admin/category.rb
class Admin::Category < ApplicationRecord

  #upload category image
  has_one_attached :image

  #define validations
  validates :name, :status , presence:true


  #relation with products table one to many
  has_many :products, dependent: :destroy



  # category image resize
  def preview

    self.image.variant(resize: '40x40!').processed
  end

  def thumbnail
    self.image.variant(resize: '100x100!').processed
  end



end

app/models/admin/customer.rb
class Admin::Customer < ApplicationRecord


end

app/models/admin/email_marketing.rb
class Admin::EmailMarketing < ApplicationRecord

  attr_accessor :send_type, :custom_email

  validates :sender_email ,  presence: true

end

app/models/admin/offer.rb
class Admin::Offer < ApplicationRecord

  require 'securerandom'

  # attr_accessor :offer_code

  before_validation(:on => :create) do
    self.offer_code = SecureRandom.hex(6)
  end

  validates :offer_name, :offer_value, :minimum_value, :start_date, :end_date, :status , presence: true
  validates :offer_value, numericality: true

end

app/models/admin/order.rb
class Admin::Order < ApplicationRecord
end

app/models/admin/product.rb
class Admin::Product < ApplicationRecord
  require 'securerandom'
  attr_accessor :name
  #upload single image
 # has_one_attached :item_images
  #upload multiple image
  has_many_attached :item_images

  validate :correct_image_type
  #realtion with category table many to one
  belongs_to :category

  before_validation(:on => :create) do
    self.item_code = SecureRandom.hex(6)
  end



  #resize image
  def small input
    return self.item_images[input].variant(resize: '80x80!').processed
  end

  def thumbnail input
    return self.item_images[input].variant(resize: '300x300!').processed
  end

  def banner
    return self.item_images.variant(resize: '900x200!').processed
  end


  private

  def correct_image_type
   if item_images.attached? == false
      errors.add(:item_images, "must have a image attached")
     elsif  item_images.each do |img|
         if !img.content_type.in?(%{image/jpeg image/png})
         errors.add(:item_images, "must be a jpeg or png")
         end
      end
    end
  end


  end

app/models/admin/setting.rb
class Admin::Setting < ApplicationRecord
  has_one_attached :logo
  has_one_attached :fevicon

  def logo_thumbnail
    self.logo.variant(resize: '100x100!').processed
  end

  def fevicon_thumbnail
    self.fevicon.variant(resize: '100x100!').processed
  end

end

app/models/admin/slider.rb
require 'Attachment'

class Admin::Slider < ApplicationRecord
  include Attachment
  # upload slider image
  has_one_attached :image

  validate :validate_image



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
require 'Attachment'

class Customer < ApplicationRecord
  include Attachment
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image
  validate :validate_image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/admin/sliders_controller.rb
class Admin::SlidersController < ApplicationController
  before_action :set_slider, only: [:show, :edit, :update, :destroy]
  before_action :set_status, only: [:new,:edit,:update,:create]
  before_action :authenticate_user!

  # GET /sliders
  # GET /sliders.json
  def index
    @sliders = Admin::Slider.all
  end

  # GET /sliders/1
  # GET /sliders/1.json
  def show
  end

  # GET /sliders/new
  def new
    @slider =Admin::Slider.new
  end

  # GET /sliders/1/edit
  def edit
  end

  # POST /sliders
  # POST /sliders.json
  def create
    @slider = Admin::Slider.new(slider_params)

    respond_to do |format|
      if @slider.save
        format.html { redirect_to admin_sliders_path, notice: 'Slider was successfully created.' }
        format.json { render :show, status: :created, location: @slider }
      else
        format.html { render :new }
        format.json { render json: @slider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sliders/1
  # PATCH/PUT /sliders/1.json
  def update
    respond_to do |format|
      if @slider.update(slider_params)
        format.html { redirect_to admin_sliders_path, notice: 'Slider was successfully updated.' }
        format.json { render :show, status: :ok, location: @slider }
      else
        format.html { render :edit }
        format.json { render json: @slider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sliders/1
  # DELETE /sliders/1.json
  def destroy
    @slider.destroy
    respond_to do |format|
      format.html { redirect_to admin_sliders_url, notice: 'Slider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slider
      @slider = Admin::Slider.find(params[:id])
    end

  def set_status
    @status = [{"name"=>"Active", "value"=>1},{"name"=>:"DeActive", "value"=>0},  ]
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slider_params
      params.require(:admin_slider).permit(:title, :description, :status, :image)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/helpers/admin/banners_helper.rb
module Admin::BannersHelper
end

app/helpers/admin/blogs_helper.rb
module Admin::BlogsHelper
end

app/helpers/admin/offers_helper.rb
module Admin::OffersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin/sliders_helper.rb
module Admin::SlidersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def controller?(*controller)
    controller.include?(params[:controller])
  end

  def action?(*action)
    action.include?(params[:action])
  end


  # view content status to list
  def status_tag(status)
    if status == 1
      content_tag( :span , "Active", :class => "label label-success")
    else
      content_tag( :span , "DeActive", :class => "label label-warning")
    end
  end

end

app/views/admin/sliders/_form.html.erb
<!-- general form elements disabled -->
<div class="col-md-8 col-md-offset-2">
  <br/>
  <br/>
  <div class="box box-warning">
    <div class="box-header with-border">
      <h3 class="box-title"><%= title %></h3>
    </div>

    <!-- /.box-header -->
    <div class="box-body">

      <% if slider.errors.any? %>

        <div class="alert alert-danger alert-dismissible">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <h4><i class="icon fa fa-ban"></i> Validations Errors!</h4>

          <ul>
            <% slider.errors.full_messages.each do  |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>

      <% end %>

      <%= form_with(model: slider, local: true) do |form|  %>

        <!-- text input -->
        <div class="form-group">
          <%= form.label :title %>
          <%= form.text_field :title, :class=> "form-control", :placeholder => "Enter ..." %>
        </div>

        <!-- text input -->
        <div class="form-group">
          <%= form.label :status %>
          <%= form.select "status", options_for_select(@status.map { |obj| [obj['name'], obj['value']] }, form.object.status ), {} , {:class => 'form-control'} %>
        </div>


        <!-- text input -->
        <div class="form-group">
          <%= form.label :description %>
          <%= form.text_area :description, :class => 'form-control'  %>
        </div>


        <div class="form-group">
          <%= form.label :slider_image %>
          <div class="row">
            <% if form.object.image.attached? && form.object.image.content_type.in?("%{image/jpeg,image/png,image/jpg}")  %>
              <%= image_tag form.object.image.variant(resize: '200x100!').processed  %>

              <%= link_to "Delete", delete_image_attachment_admin_category_url(form.object.image.id),
                          method: :delete,
                          data: { confirm: 'Are you sure?' },  :class => "label label-danger" %>
            <% end %>
          </div>

          <%= form.file_field :image, :class => "form-control" %>
        </div>

        <%= form.submit :class => "btn btn-success pull-right" %>



      <% end %>




      <%= link_to "Back" , admin_sliders_path , :class => "btn btn-warning "%>

    </div>
  </div>
</div>

app/views/admin/sliders/edit.html.erb
<%= render 'form', slider: @slider, title: "Edit slider" %>

app/views/admin/sliders/index.html.erb
<div class="box">
  <div class="box-header">
    <h3 class="box-title">Sliders </h3>
    <div class="pull-right">
      <%= link_to "Add New", new_admin_slider_path, :class => "btn btn-primary"  %>
    </div>

    <div class="row">
      <% if notice %>
        <div class="col-md-6 col-md-offset-3">
          <div class="alert alert-success alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <h4><i class="icon fa fa-check"></i> Message!</h4>
            <%= notice %>
          </div>
        </div>
      <% end %>
    </div>


  </div>
  <!-- /.box-header -->
  <div class="box-body">

    <table id="example1" class="table table-bordered table-striped">
      <thead>
      <tr>
        <th>Title</th>
        <th>Status</th>
        <th>Description</th>
        <th>Image</th>
        <th>Action</th>
      </tr>
      </thead>
      <tbody>
      <% @sliders.each do |slider| %>

        <tr>
          <td><%= slider.title %></td>
          <td>
            <% if slider.status == 1 %>
              <span class="label label-success">Active</span>
            <% else %>
              <span class="label label-warning">DeActive</span>
            <% end %>

          </td>
          <td><%= slider.description %></td>
          <td>
            <% if slider.image.attached? %>
              <%= image_tag slider.image.variant(resize: '100x50!').processed %>
            <% end %>

          </td>
          <td>

            <%= link_to edit_admin_slider_path(slider) , :class=> "btn btn-success" do %>
              <%= fa_icon "edit" %>
            <% end %>

            <%= link_to slider, method: :delete , data: { confirm: "Are you sure ? "} ,:class =>"btn btn-danger" do %>
              <%= fa_icon "trash" %>
            <% end %>

          </td>
        </tr>

      <% end %>


      </tbody>
    </table>
  </div>
</div>

app/views/admin/sliders/new.html.erb
<%= render 'form', slider: @slider, title: "Add new slider" %>

app/views/admin/sliders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @slider.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @slider.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @slider.status %>
</p>

<%= link_to 'Edit', edit_slider_path(@slider) %> |
<%= link_to 'Back', sliders_path %>