config/routes.rb
Rails.application.routes.draw do

  namespace :admin do

    resources :orders
    resources :banners
    resources :email_marketings
    resources :offers

    resources :blogs
    resources :sliders
    resources :customers , only: [:index,:edit,:update,:destroy]



    resources :categories

    resources :products

    resources :settings


    resources :products do
      member do
        delete :delete_image_attachment
      end
    end
    resources :categories do
      member do
        delete :delete_image_attachment
      end
    end



  end

# get "blogs", to: 'blogs#index'



  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      confirmations: 'users/confirmations',
  }

  devise_for :customers, controllers: {
      sessions: 'customers/sessions',
      registrations: 'customers/registrations',
      passwords: 'customers/passwords',
      confirmations: 'customers/confirmations',
  }

  resources :users


  get "/admin", to: 'admin/dashboard#index'

  root 'admin/dashboard#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/banner.rb
require 'Attachment'
class Admin::Banner < ApplicationRecord
  include Attachment
  # accept banner image
  has_one_attached :image

  # velidate image only
  validate :validate_image

end

app/models/admin/blog.rb
require 'Attachment'

class Admin::Blog < ApplicationRecord

  include Attachment

  has_one_attached :image

  # validate image file
  validate :validate_image



end

app/models/admin/category.rb
class Admin::Category < ApplicationRecord

  #upload category image
  has_one_attached :image

  #define validations
  validates :name, :status , presence:true


  #relation with products table one to many
  has_many :products, dependent: :destroy



  # category image resize
  def preview

    self.image.variant(resize: '40x40!').processed
  end

  def thumbnail
    self.image.variant(resize: '100x100!').processed
  end



end

app/models/admin/customer.rb
class Admin::Customer < ApplicationRecord


end

app/models/admin/email_marketing.rb
class Admin::EmailMarketing < ApplicationRecord

  attr_accessor :send_type, :custom_email

  validates :sender_email ,  presence: true

end

app/models/admin/offer.rb
class Admin::Offer < ApplicationRecord

  require 'securerandom'

  # attr_accessor :offer_code

  before_validation(:on => :create) do
    self.offer_code = SecureRandom.hex(6)
  end

  validates :offer_name, :offer_value, :minimum_value, :start_date, :end_date, :status , presence: true
  validates :offer_value, numericality: true

end

app/models/admin/order.rb
class Admin::Order < ApplicationRecord
end

app/models/admin/product.rb
class Admin::Product < ApplicationRecord
  require 'securerandom'
  attr_accessor :name
  #upload single image
 # has_one_attached :item_images
  #upload multiple image
  has_many_attached :item_images

  validate :correct_image_type
  #realtion with category table many to one
  belongs_to :category

  before_validation(:on => :create) do
    self.item_code = SecureRandom.hex(6)
  end



  #resize image
  def small input
    return self.item_images[input].variant(resize: '80x80!').processed
  end

  def thumbnail input
    return self.item_images[input].variant(resize: '300x300!').processed
  end

  def banner
    return self.item_images.variant(resize: '900x200!').processed
  end


  private

  def correct_image_type
   if item_images.attached? == false
      errors.add(:item_images, "must have a image attached")
     elsif  item_images.each do |img|
         if !img.content_type.in?(%{image/jpeg image/png})
         errors.add(:item_images, "must be a jpeg or png")
         end
      end
    end
  end


  end

app/models/admin/setting.rb
class Admin::Setting < ApplicationRecord
  has_one_attached :logo
  has_one_attached :fevicon

  def logo_thumbnail
    self.logo.variant(resize: '100x100!').processed
  end

  def fevicon_thumbnail
    self.fevicon.variant(resize: '100x100!').processed
  end

end

app/models/admin/slider.rb
require 'Attachment'

class Admin::Slider < ApplicationRecord
  include Attachment
  # upload slider image
  has_one_attached :image

  validate :validate_image



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
require 'Attachment'

class Customer < ApplicationRecord
  include Attachment
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image
  validate :validate_image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < ApplicationController
  before_action :set_settings, only: [:edit,:update,:destroy]
  before_action :authenticate_user!


  def index
  @settings = Admin::Setting.all
  end

  def new
    @setting = Admin::Setting.new
  end

  def create
    @setting = Admin::Setting.new(setting_params)
    if @setting.save
      redirect_to admin_settings_path
    else
      render :new
    end
  end


  def update
    @setting.update(setting_params)
    redirect_to admin_settings_path , notice: "Settings Updated"
  end


  def destory
    @setting.destroy
    redirect_to admin_settings_path, notice: "Settings Deleted"
  end



  private

  def set_settings
    @setting = Admin::Setting.find(params[:id])
  end

  def setting_params
    params.require(:admin_setting).permit(:company_name,:company_title,
                                    :company_phone,:company_email,
                                    :company_address,:company_about,
                                    :company_location,:company_facebook,:company_twitter,
                                    :comapny_youtube,:company_other,:logo,:fevicon,)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/helpers/admin/banners_helper.rb
module Admin::BannersHelper
end

app/helpers/admin/blogs_helper.rb
module Admin::BlogsHelper
end

app/helpers/admin/offers_helper.rb
module Admin::OffersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/settings_helper.rb
module Admin::SettingsHelper
end

app/helpers/admin/sliders_helper.rb
module Admin::SlidersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def controller?(*controller)
    controller.include?(params[:controller])
  end

  def action?(*action)
    action.include?(params[:action])
  end


  # view content status to list
  def status_tag(status)
    if status == 1
      content_tag( :span , "Active", :class => "label label-success")
    else
      content_tag( :span , "DeActive", :class => "label label-warning")
    end
  end

end

app/views/admin/settings/_form.html.erb
<!-- general form elements disabled -->
<div class="col-md-8 col-md-offset-2">
  <br/>
  <br/>
  <div class="box box-warning">
    <div class="box-header with-border">
      <h3 class="box-title"><%= title %></h3>
    </div>

    <!-- /.box-header -->
    <div class="box-body">

      <% if setting.errors.any? %>

        <div class="alert alert-danger alert-dismissible">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <h4><i class="icon fa fa-ban"></i> Validations Errors!</h4>

          <ul>
            <% setting.errors.full_messages.each do  |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>

      <% end %>

      <%= form_with(model: setting, local: true) do |form|  %>

        <!-- text input -->
        <div class="form-group">
          <%= form.label :company_name %>
          <%= form.text_field :company_name, :class=> "form-control"%>
        </div>

        <!-- text input -->
        <div class="form-group">
          <%= form.label :company_title %>
          <%= form.text_field :company_title, :class=> "form-control"%>
        </div>

        <!-- text input -->
        <div class="form-group">
          <%= form.label :company_phone %>
          <%= form.text_field :company_phone, :class=> "form-control"%>
        </div>

        <!-- text input -->
        <div class="form-group">
          <%= form.label :company_email %>
          <%= form.email_field :company_email, :class=> "form-control"%>
        </div>

        <!-- text input -->
        <div class="form-group">
          <%= form.label :company_address %>
          <%= form.text_area :company_address, :class => 'form-control'  %>
        </div>

        <!-- text input -->
        <div class="form-group">
          <%= form.label :company_about %>
          <%= form.text_area :company_about, :class => 'form-control'  %>
        </div>


        <!-- text input -->
        <div class="form-group">
          <%= form.label :company_facebook %>
          <%= form.text_field :company_facebook, :class=> "form-control"%>
        </div>

        <!-- text input -->
        <div class="form-group">
          <%= form.label :company_twitter %>
          <%= form.text_field :company_twitter, :class=> "form-control"%>
        </div>

        <!-- text input -->
        <div class="form-group">
          <%= form.label :company_youtube %>
          <%= form.text_field :company_youtube, :class=> "form-control"%>
        </div>

        <!-- text input -->
        <div class="form-group">
          <%= form.label :company_other_link %>
          <%= form.text_field :company_other, :class=> "form-control"%>
        </div>

        <!-- text input -->
        <div class="form-group">
          <%= form.label :company_location %>
          <%= form.text_field :company_location, :class=> "form-control"%>
        </div>



        <div class="form-group">
          <%= form.label :company_logo %>
          <div class="row">
            <% if form.object.logo.attached? && form.object.logo.content_type.in?("%{image/jpeg,image/png,image/jpg}")  %>
              <%= image_tag form.object.logo_thumbnail  %>

              <%= link_to "Delete", delete_image_attachment_category_url(form.object.logo.id),
                          method: :delete,
                          data: { confirm: 'Are you sure?' },  :class => "label label-danger" %>
            <% end %>
          </div>

          <%= form.file_field :logo, :class => "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :company_fevicon %>
          <div class="row">
            <% if form.object.fevicon.attached? && form.object.fevicon.content_type.in?("%{image/jpeg,image/png,image/jpg}")  %>
              <%= image_tag form.object.fevicon_thumbnail  %>

              <%= link_to "Delete", delete_image_attachment_category_url(form.object.fevicon.id),
                          method: :delete,
                          data: { confirm: 'Are you sure?' },  :class => "label label-danger" %>
            <% end %>
          </div>

          <%= form.file_field :fevicon, :class => "form-control" %>
        </div>

        <%= form.submit :class => "btn btn-success pull-right" %>



      <% end %>




      <%= link_to "Back" , admin_categories_path , :class => "btn btn-warning "%>

    </div>
  </div>
</div>

app/views/admin/settings/edit.html.erb
<%= render "form", setting: @setting, title: "Update setting" %>

app/views/admin/settings/index.html.erb
<div class="box">
  <div class="box-header">
    <h3 class="box-title">Setting </h3>
    <div class="pull-right">
      <%= link_to "Add New", new_admin_setting_path, :class => "btn btn-primary"  %>
    </div>

    <div class="row">
      <% if notice %>
        <div class="col-md-6 col-md-offset-3">
          <div class="alert alert-success alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <h4><i class="icon fa fa-check"></i> Message!</h4>
            <%= notice %>
          </div>
        </div>
      <% end %>
    </div>


  </div>
  <!-- /.box-header -->
  <div class="box-body">

    <table id="example1" class="table table-bordered table-striped">
      <thead>
      <tr>
        <th>Company Name</th>
        <th>Title</th>
        <th>Phone</th>
        <th>Email</th>
        <th>Address</th>
        <th>Logo</th>
        <th>Fevicon</th>
        <th>Action</th>
      </tr>
      </thead>
      <tbody>
      <% @settings.each do |setting| %>

        <tr>
          <td><%= setting.company_name %></td>
          <td><%= setting.company_title %></td>
          <td><%= setting.company_phone %></td>
          <td><%= setting.company_email %></td>
          <td><%= setting.company_address %></td>
          <td>
            <% if setting.logo.attached? %>
              <%= image_tag setting.logo_thumbnail %>
            <% end %>
          </td>
          <td>
            <% if setting.fevicon.attached? %>
              <%= image_tag setting.fevicon_thumbnail %>
            <% end %>
          </td>

          <td>

            <%= link_to edit_admin_setting_path(setting) , :class=> "btn btn-success" do %>
              <%= fa_icon "edit" %>
            <% end %>

            <%= link_to setting, method: :delete , data: { confirm: "Are you sure ? "} ,:class =>"btn btn-danger" do %>
              <%= fa_icon "trash" %>
            <% end %>

          </td>
        </tr>

      <% end %>


      </tbody>
    </table>
  </div>
</div>

app/views/admin/settings/new.html.erb
<%= render "form", setting: @setting, title: "Add Settings" %>