config/routes.rb
Rails.application.routes.draw do

  namespace :admin do

    resources :orders
    resources :banners
    resources :email_marketings
    resources :offers

    resources :blogs
    resources :sliders
    resources :customers , only: [:index,:edit,:update,:destroy]



    resources :categories

    resources :products

    resources :settings


    resources :products do
      member do
        delete :delete_image_attachment
      end
    end
    resources :categories do
      member do
        delete :delete_image_attachment
      end
    end



  end

# get "blogs", to: 'blogs#index'



  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords',
      confirmations: 'users/confirmations',
  }

  devise_for :customers, controllers: {
      sessions: 'customers/sessions',
      registrations: 'customers/registrations',
      passwords: 'customers/passwords',
      confirmations: 'customers/confirmations',
  }

  resources :users


  get "/admin", to: 'admin/dashboard#index'

  root 'admin/dashboard#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin/email_marketing.rb
class Admin::EmailMarketing < ApplicationRecord

  attr_accessor :send_type, :custom_email

  validates :sender_email ,  presence: true

end

app/controllers/admin/email_marketings_controller.rb
class Admin::EmailMarketingsController < ApplicationController
  before_action :set_email_marketing, only: [:show, :edit, :update, :destroy]
  before_action :set_customer, only: [:new, :edit, :create, :update]

  # GET /email_marketings
  # GET /email_marketings.json
  def index
    @email_marketings = Admin::EmailMarketing.all
  end

  # GET /email_marketings/1
  # GET /email_marketings/1.json
  def show
  end

  # GET /email_marketings/new
  def new
    @email_marketing = Admin::EmailMarketing.new
  end

  # GET /email_marketings/1/edit
  def edit
  end

  # POST /email_marketings
  # POST /email_marketings.json
  def create

   # render plain: params[:admin_email_marketing][:send_type]

     @email_marketing = Admin::EmailMarketing.new(email_marketing_params)

     @send_type = params[:admin_email_marketing][:send_type]
     if @send_type == "All"
       @email_marketing.reciver_email = "All"
     elsif @send_type == "Custom Email"
       @email_marketing.reciver_email = params[:admin_email_marketing][:custom_email]
     end

    respond_to do |format|
      if @email_marketing.save
        # Tell the UserMailer to send a welcome email after save

        if @email_marketing.reciver_email == "All"

          #find all the customer and send email
          Customer.find_each do |customer|
            @email_marketing.reciver_email = customer.email
            EmailMarketingMailer.with(email: @email_marketing ).send_email.deliver_now
          end
        else

          EmailMarketingMailer.with(email: @email_marketing ).send_email.deliver_now

          end

        format.html { redirect_to admin_email_marketings_path, notice: 'Email marketing was successfully created.' }
        format.json { render :show, status: :created, location: @email_marketing }
      else
        format.html { render :new }
        format.json { render json: @email_marketing.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /email_marketings/1
  # PATCH/PUT /email_marketings/1.json
  def update
    respond_to do |format|
      if @email_marketing.update(email_marketing_params)
        # Tell the UserMailer to send a welcome email after save
        @email = Admin::EmailMarketing.last

        EmailMarketingMailer.with(email: @email).send_email.deliver_now

        format.html { redirect_to admin_email_marketings_path, notice: 'Email marketing was successfully updated.' }
        format.json { render :show, status: :ok, location: @email_marketing }
      else
        format.html { render :edit }
        format.json { render json: @email_marketing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /email_marketings/1
  # DELETE /email_marketings/1.json
  def destroy
    @email_marketing.destroy
    respond_to do |format|
      format.html { redirect_to admin_email_marketings_url, notice: 'Email marketing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # customer list for sending email
    def set_customer
      @customers = Admin::Customer.all
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_email_marketing
      @email_marketing = Admin::EmailMarketing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def email_marketing_params
      params.require(:admin_email_marketing).permit(:sender_name, :sender_email, :email_subject, :email_body, :reciver_email)
    end
end

app/helpers/admin/email_marketings_helper.rb
module Admin::EmailMarketingsHelper
end

app/views/admin/email_marketings/_form.html.erb
<!-- general form elements disabled -->
<div class="col-md-8 col-md-offset-2">
  <br/>
  <br/>
  <div class="box box-warning">
    <div class="box-header with-border">
      <h3 class="box-title"><%= title %></h3>
    </div>

    <!-- /.box-header -->
    <div class="box-body">

      <% if email_marketing.errors.any? %>

        <div class="alert alert-danger alert-dismissible">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <h4><i class="icon fa fa-ban"></i> Validations Errors!</h4>

          <ul>
            <% email_marketing.errors.full_messages.each do  |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>

      <% end %>

      <%= form_with(model: email_marketing, local: true) do |form|  %>

        <!-- text input -->
        <div class="form-group">
          <%= form.label :sender_name %>
          <%= form.text_field :sender_name , :class=>"form-control", :placeholder=>"Enter..." %>
        </div>


        <!-- text input -->
        <div class="form-group">
          <%= form.label :sender_email %>
          <%= form.email_field :sender_email , :class=>"form-control", :placeholder=>"Enter..." %>
        </div>


        <div class="form-group">

          <%= form.label :send_type %>
          <%= form.select(:send_type, ["All", "Selected Customer", "Custom Email"], {}, {:class => "form-control"}) %>
        </div>

        <!-- text input -->
        <div class="form-group" style="display:none" id="reciver_email">
          <%= form.label :reciver_email %>
          <%#= form.email_field :reciver_email , :class=>"form-control", :placeholder=>"Enter..." %>
          <%= form.select("reciver_email", options_for_select(@customers.map { |obj| [obj['name'], obj['email']]}, form.object.reciver_email), {}, {:class => "form-control"} ) %>
        </div>

        <!-- text input -->
        <div class="form-group" style="display:none" id="reciver_custom_email">
          <%= form.label :custom_email %>
          <%= form.email_field :custom_email , :class=>"form-control", :placeholder=>"Enter..." %>

        </div>

        <!-- text input -->
        <div class="form-group">
          <%= form.label :email_subject %>
          <%= form.text_field :email_subject , :class=>"form-control", :placeholder=>"Enter..." %>
        </div>




        <div class="form-group">
          <%= form.label :email_body %>
          <%= form.text_area :email_body, rows: 5, cols: 25, :class => "tinymce" %>
        </div>


        <%= form.submit :value => "Send Email Now", :class => "btn btn-success pull-right" %>

      <% end %>

      <%= link_to "Back" , admin_email_marketings_path , :class => "btn btn-warning "%>
      <%= tinymce %>
    </div>
  </div>
</div>

app/views/admin/email_marketings/edit.html.erb
 <%= render 'form', email_marketing: @email_marketing, title: "Update email" %>

app/views/admin/email_marketings/index.html.erb
<div class="box">
  <div class="box-header">
    <h3 class="box-title">All Categories </h3>
    <div class="pull-right">
      <%= link_to "Add New", new_admin_email_marketing_path, :class => "btn btn-primary"  %>
    </div>

    <div class="row">
      <% if notice %>
        <div class="col-md-6 col-md-offset-3">
          <div class="alert alert-success alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <h4><i class="icon fa fa-check"></i> Message!</h4>
            <%= notice %>
          </div>
        </div>
      <% end %>
    </div>


  </div>
  <!-- /.box-header -->
  <div class="box-body">

    <table id="example1" class="table table-bordered table-striped">
      <thead>
      <tr>
        <th>Sender Name</th>
        <th>Sender Email</th>
        <th>Reciver Email</th>
        <th>Email Subject</th>
        <th>Send Date</th>
        <th>Action</th>
      </tr>
      </thead>
      <tbody>
      <% @email_marketings.each do |email_marketing| %>

        <tr>
          <td><%= email_marketing.sender_name %></td>
          <td><%= email_marketing.sender_email %></td>
          <td><%= email_marketing.reciver_email %></td>
          <td><%= email_marketing.email_subject %></td>
          <td><%= email_marketing.created_at %></td>
          <td>

            <%= link_to edit_admin_email_marketing_path(email_marketing) , :class=> "btn btn-success" do %>
              <%= fa_icon "edit" %>
            <% end %>

            <%= link_to email_marketing, method: :delete , data: { confirm: "Are you sure ? "} ,:class =>"btn btn-danger" do %>
              <%= fa_icon "trash" %>
            <% end %>

          </td>
        </tr>

      <% end %>


      </tbody>
    </table>
  </div>
</div>

app/views/admin/email_marketings/new.html.erb
 <%= render 'form', email_marketing: @email_marketing, title: "Compose new email" %>

app/views/admin/email_marketings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sender name:</strong>
  <%= @email_marketing.sender_name %>
</p>

<p>
  <strong>Sender email:</strong>
  <%= @email_marketing.sender_email %>
</p>

<p>
  <strong>Reciver email:</strong>
  <%= @email_marketing.reciver_email %>
</p>

<p>
  <strong>Email subject:</strong>
  <%= @email_marketing.email_subject %>
</p>

<p>
  <strong>Email body:</strong>
  <%= @email_marketing.email_body %>
</p>

<%= link_to 'Edit', edit_email_marketing_path(@email_marketing) %> |
<%= link_to 'Back', email_marketings_path %>